apiVersion: v1
kind: Service
metadata:
  name: hce-middleware-service
spec:
  selector:
    app: hce-middleware
  type: NodePort  # Tipo para exponer el servicio fuera del clúster Minikube
  ports:
    - protocol: TCP
      port: 80     # Puerto interno del servicio K8s
      targetPort: 8000 # Puerto del contenedor Uvicorn
      nodePort: 30000 # Puerto accesible desde tu máquina (Minikube)